### ISSUE TITLE
Is there support for OrderedDict

### ISSUE THREAD

**Issue by pumelo** [Scille/umongo#55]
If you like to find embedded documents the order of the kv pairs in the embedded document is essential as 'find' will only match documents with the same order. As the mongo docs say (https://docs.mongodb.com/manual/tutorial/query-documents/#exact-match-on-the-embedded-document):

> Equality matches on an embedded document require an exact match of the specified <value>, including the field order.

pymongo thus supports python OrderedDict: 
http://stackoverflow.com/a/30787769/4273834

as does marshmallow:
http://marshmallow.readthedocs.io/en/latest/quickstart.html#ordering-output

Is there a way to use OrderedDict in umongo?

**Comment by touilleMan** [comment]
Thanks for the issue !

For the moment umongo serialize it document as regular python `dict` (see the output of `Document.to_mongo` method).

Given it's this data which is in turn provided to the underlying pymongo, we have no way to ensure the order of the fields stored in the db.
The solution would be to make `Document.to_mongo` returns a `bson.son.SON` (with keys in they order of declaration for example) instead.


The query system should be improved as well: currently if you do `MyDocument.find({my_field: "whatever"})`, a pass is done on the query filter to replace the field name by they real name in mongodb if it differs. We should use this pass to correct fields referring to embedded document to turn them into `OrderedDict`.

What do you think ?

**Comment by lafrech** [comment]
Random thought: another way would be to store as `dict` as usual and add as hidden attribute a list of the fields, in order. On deserialization, the `OrderedDict` could use that list to get its order.

This does not look as elegant as @touilleMan's proposal, but if that proposal revealed complicated, this could be a fallback scenario.

**Comment by lafrech** [comment]
What about always sorting the keys in alphabetic order when dumping to Mongo?

This won't help for use cases where the database is pre-existing or also written by another mean, but it would solve the umongo use case easily, wouldn't it?

**Comment by lafrech** [comment]
Wondering if this is automagically solved in Python 3.7 thanks to all dicts being ordered.

**Comment by lafrech** [comment]
From Python 3.7 on, schemas are ordered and fields are recorded in database in schema order.

Therefore, you can't save documents in any arbitrary order, but at least the order is deterministic. This means that you can't distinguish two inputs with different orders, the order is lost, but at least you can query without the order screwing up the match. Just ensure the dict in the query is in the same order as the fields in the schema.

This is not perfect as it requires the user to be aware of the schema field order when querying. We could try to tweak the query automatically according to the schema, but that sounds like too much trouble for the use case.

**Comment by lafrech** [comment]
One should be able to abstract the order by passing an EmbeddedDocument instance thanks to #303.

**Comment by samypr100** [comment]
@lafrech I tried testing part of this on uMongo 3.0.0b13, and Python 3.8 using both Pymongo Instance and Motor Instance and fields still do not preserve order on insertion (via `.commit`).

Also tried defining my own ma.Schema but no luck.
```python
class OrderedSchema(ma.Schema):
    class Meta:
        ordered = True
```

**Comment by lafrech** [comment]
Reopening for further investigation.

**Comment by lafrech** [comment]
> From Python 3.7 on, schemas are ordered and fields are recorded in database in schema order.

This is wrong. Because ordered schemas rely on OrderedDict but also on OrderedSet internally. See marshmallow code for more details. I always figured schemas would be naturally ordered with Python 3.7 but it is not the case. It could be worth changing this in marshmallow because with all dicts being ordered, the cost of ordering becomes much lower and it could become the default, but it is not the case in the foreseeable future.

----------------------------------

Adding

```py
    class Meta:
        ordered = True
```
to `BaseSchema` seems to fix this since it ensures the order is preserved on schema dump and the rest of the chain preserves the order as well (Python >= 3.7).

@samypr100 see #323.

**Comment by samypr100** [comment]
Confirmed Working

**Comment by lafrech** [comment]
Great. Thanks @samypr100 for confirming.
